### ISSUE TITLE
Remove ackack

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#126]
Steps to remove it:

* [x] Send drop messages without ackack in QabelService
* [x] Receive drop messages without ackack in QabelService
* [x] Manage identities without ackack in QabelService and LocalQabelService
* [x] Manage contacts without ackack in QabelService and LocalQabelService
* [x] Propagate events with a decent event system instead of ackack

**Comment by audax** [comment]
@L-Henke Let's do it. The desktop devs don't want to use it either. We can keep the QabelService and improve the LocalQabelService so we can still propagate the change events.

**Comment by L-Henke** [comment]
For Android related needs of an event system I can recommend https://github.com/greenrobot/EventBus

**Comment by dannywerner** [comment]
remove deprecated ackack from public github repository
