### ISSUE TITLE
Save database password in KeyStore

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#131]
https://developer.android.com/about/versions/android-4.3.html#Security

See #120 which removed the password entering.

**Comment by audax** [comment]
New plan:

1. Generate a password
2. Generate a private key and save it in the KeyStore
3. Encrypt the password with the key and save it in the sharedPreferences

**Comment by audax** [comment]
Not easily possible in Android API level <23 because there is no proper way to access the private key of a generated certificate.

For now, the encryption will just be disabled.

**Comment by L-Henke** [comment]
"Not easily possible in Android API level <23 because there is no proper way to access the private key of a generated certificate."

Why would we need the private part of a certificate? We would need the private part of a normal key pair.
