### ISSUE TITLE
Send and receive drop messages through QabelService

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#137]
* [ ] Send drop messages without ackack in QabelService
* [ ] Receive drop messages without ackack in QabelService

Since AckAck was removed from the android app and there are no non-ackack ways defined in the qabel-core to send and receive drop messages, this part should be reimplemented in the LocalQabelService and then maybe backported to the qabel-core.

Needed for #30 and #22 and all the other share and messaging related tasks.

**Comment by audax** [comment]
Changes in core made in https://github.com/Qabel/qabel-core/pull/429

**Comment by L-Henke** [comment]
Closed by https://github.com/Qabel/qabel-android/pull/194
