### ISSUE TITLE
License stuff, privacy policy and toc, impressum

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#139]
* [ ] source headers
* [ ] show license information (QPL and third parties) in application
* [ ] toc and privacy policy
* [ ] impressum
* [ ] contact/support info/help

**Comment by audax** [comment]
See #155

**Comment by thechauffeur** [comment]
I will think about source headers, otherwise go ahead.

**Comment by dannywerner** [comment]
add features in sidemenu under help. add menu entrys:
- license information
- data policy
- contact
- disclaimer
- about (show app build date, version number)
depends from #153

**Comment by dannywerner** [comment]
add default inapp webviewerfragment and link to webpages with information to asset directory, fix css to app fonts (roboto). check on different devices

**Comment by dannywerner** [comment]
iam need the final content text:
disclaimer
terms of use
data policy

**Comment by jmt85** [comment]
yes, we are waiting too. 
Use lorem ipsum for everything missing,

**Comment by dannywerner** [comment]
lorem ipsum is implemented.

**Comment by mr-gosh** [comment]
in the "About" Dialog - the "legal notes" and the "privacy notes" from the 5th welcome screen need to be implemented.
Also there need to be an "impressum" - like an the websites.

Some of this stuff is also mentioned in the "help" dialog - which is wrong!

**Comment by mr-gosh** [comment]
![help-dialog](https://cloud.githubusercontent.com/assets/3028703/13668020/28a1ff6c-e6ba-11e5-9855-2d8028c425cc.png)

**Comment by mr-gosh** [comment]
![about_dialog](https://cloud.githubusercontent.com/assets/3028703/13668269/04802404-e6bc-11e5-8e78-5572965d10b2.png)
