### ISSUE TITLE
create bug reporting for android

### ISSUE THREAD

**Issue by dannywerner** [Qabel/qabel-android#140]
add functions to get app crashs.

**Comment by thechauffeur** [comment]
An idea is to use hockey app at least for development and closed beta versions.

**Comment by dannywerner** [comment]
if we use hockeyapp, someone must create a account at http://hockeyapp.net and send me login data.

hockey app accounts support multi user logins with different roles

**Comment by dannywerner** [comment]
if we use hockeyapp we can build small scripts for jenkins to auto-upload the nightly builds into hockeyapp so all 'certain' users can get the newest version every day
e.g. https://wiki.jenkins-ci.org/display/JENKINS/HockeyApp+Plugin

**Comment by dannywerner** [comment]
http://hockeyapp.net/apps/

**Comment by thechauffeur** [comment]
We now use HocleyApp. Get in touch with @dannywerner for further information.

**Comment by dannywerner** [comment]
The key must places in existing aws_credentials.xml 
    <string name="hockeykey">XXXXXX-APP-KEY</string>
