### ISSUE TITLE
Using cached data for the search

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#145]
Instead of crawling the volume every time, the search function should use the cached data first and have a method to force a cache-refresh for the search cache.

**Comment by dave0100** [comment]
Please note that you can reuse a once initialized StorageSearch (it's intended to just crawl once on app startup), and build a search from a cache using

public StorageSearch(List<BoxObject> results, Hashtable<String, BoxObject> pathMapping)

**Comment by dannywerner** [comment]
@dave0100 how can iam refresh the search result? 
iam can clone the storagesearch... but iam want to refresh the result after the user make changes, like delete, upload ...

**Comment by audax** [comment]
We don't keep the search cache up to date. We first deliver search results from the current cache (which may be outdated of course!), but we instantly start a new search with fresh data in the background while we show a nice spinner next to the search-symbol.

**Comment by dannywerner** [comment]
Add functions to testscript to automatic create box account and upload files before tests startet
