### ISSUE TITLE
Organize drawables

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#148]
Currently, the drawables are not organized. We have to use the proper icons provided by the mockups.

**Comment by audax** [comment]
For example: Remove drawable-mdpi folder.

**Comment by dannywerner** [comment]
check names, all fragment.xmls should start with fragment_xxxx.xml, all list items  with item_xxxx.xml, all action bar layouts should start with ab_xxxx.xml, all icons for actionbar with ic_ab_xxxxx.xml
