### ISSUE TITLE
Create Splashscreen

### ISSUE THREAD

**Issue by dannywerner** [Qabel/qabel-android#151]

**Comment by mr-gosh** [comment]
Splash screen is done - where to upload it?

**Comment by mr-gosh** [comment]
I just left it in Issue 3988 in the redmine...

**Comment by thechauffeur** [comment]
@mr-gosh you should have assigned @dannywerner again.

**Comment by audax** [comment]
Fixed by #175

**Comment by mr-gosh** [comment]
@dannywerner here the Logo (orange on transparent - HiRes)
![qabel-logo-full-orange](https://cloud.githubusercontent.com/assets/3028703/12358349/14d514fc-bbad-11e5-98e7-44227303043c.png)

And The Clouds for the Bottom (orange on transparent - HiRes)
![clouds](https://cloud.githubusercontent.com/assets/3028703/12358469/a98f489c-bbad-11e5-9a34-516decd5ae78.png)

Which sentences to Display was already sent to you, right?
