### ISSUE TITLE
Create welcome/whatsnew screen

### ISSUE THREAD

**Issue by dannywerner** [Qabel/qabel-android#153]
Create design for flexibel welcome/whatsnew screen

**Comment by mr-gosh** [comment]
Welcome Screens are prepared.
Final Sentences and background image will follow.

![welcome_1](https://cloud.githubusercontent.com/assets/3028703/13107492/3d56339a-d56e-11e5-9eb3-2685828703d5.png)
![welcome_2](https://cloud.githubusercontent.com/assets/3028703/13107496/43f3b22c-d56e-11e5-8d98-9808e5fac53d.png)
![welcome_3](https://cloud.githubusercontent.com/assets/3028703/13107501/46ad401e-d56e-11e5-830e-9998085ae230.png)
![welcome_4](https://cloud.githubusercontent.com/assets/3028703/13107499/46acbb6c-d56e-11e5-8242-4485a53cdb67.png)
![welcome_5](https://cloud.githubusercontent.com/assets/3028703/13107500/46ad2de0-d56e-11e5-91fc-e4a896e3d41a.png)

**Comment by dannywerner** [comment]
additional, implements this on android
