### ISSUE TITLE
Add message if no net access available

### ISSUE THREAD

**Issue by hash13** [Qabel/qabel-android#162]
When the user start the app until the phone is offline, the file browser fragment are empty and no message showed
- check if device online and inform user 
- maybe the user should inform on any action that network access required and initilize from user (ui)

**Comment by wischweh** [comment]
i would recommend postponing this to after the refactoring. At the moment, due to the spaghetti nature of the code base it would mean hardcoding checks at many different places, easily missing one

**Comment by audax** [comment]
We postpone it.

**Comment by dannywerner** [comment]
other errors: if iam set phone to flight mode, the app can't load box directory and the loading bar is endless. after iam setting phone in normal mode (internet available), the pull to refresh dont refreshing and the loading bar nevers ends. a new pull to refresh is at this place not available. pls defeine timeout for server communication and handle server errors

other thins is that the phone show both load indicators.

**Comment by dannywerner** [comment]
![network](https://cloud.githubusercontent.com/assets/5576400/14240475/79f218ae-fa45-11e5-86ca-89fcec66300b.png)

**Comment by JoGir** [comment]
i am currently working on this
