### ISSUE TITLE
Please don't do heavy things in service/main thread

### ISSUE THREAD

**Issue by dannywerner** [Qabel/qabel-android#174]
currently the app start a new service at appstart (LocalQabelService, startet from QabelBoxApplication and other, defined in manifest) and do some heavy things (cpu time).

by default, a service runs in the same process as the main thread of the application and blocks ui.
If a servce blocks ui too long we get a ANR (application not response) error.

therefore, you need to use asynchronous processing in the service to perform resource intensive tasks in the background. a commonly used pattern for a service implementation is to create and run a new Thread in the service to perform the processing in the background and then to terminate the service once it has finished the processing. 

please check the android services which parts blocks the ui

http://developer.android.com/reference/android/app/Service.html

**Comment by audax** [comment]
#182 reduce the CPU time greatly by reducing the amount of PBKDF2 rounds for the (ineffective because it is disabled) local database encryption.

This is however relevant to the sending and receiving of drop messages in #137.
