### ISSUE TITLE
Create license list of used libs and other stuff

### ISSUE THREAD

**Issue by dannywerner** [Qabel/qabel-android#189]
- create list of used third party librarys
- holo theme generator
- check if assets are under license model, (fonts, images,  CC-BY 4.0,
e.g.
http://google.github.io/material-design-icons/#getting-icons
and other

**Comment by audax** [comment]
Mockup done for this by @mr-gosh

**Comment by wischweh** [comment]
Here is the licencing info:

Qabel Licence
- Qabel


Apache 2
- Apache Commons
- Android Open Source Project
- GSON
- Apache Httpcomponents
- ZXing
- (Hockey SDK)
- Bottomsheet
- OkHttp
- Picasso

Bouncy Castle Licence
- Spongy Castle

Hockey SDK Licence
- (c) Microsoft Licence: https://github.com/bitstadium/HockeySDK-Android/blob/develop/LICENSE (permissive, no copy left)

MIT Licence
- SLF4J
- SQLDroid 1.0.3
- (Hockey SDK)

**Comment by mr-gosh** [comment]
Material Design Icons:
Google Material Design Icons - Attribution 4.0 International
https://github.com/google/material-design-icons/blob/master/LICENSE

Material Design Icons - based Icons:
Community Icons - SIL Open Font License 1.1
http://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web

License for 'Roboto' Font:
Apache License - Font data copyright Google 2012
                      Apache License
                  Version 2.0, January 2004
                http://www.apache.org/licenses/
