### ISSUE TITLE
Images can't open

### ISSUE THREAD

**Issue by dannywerner** [Qabel/qabel-android#191]
If the user click in filebrowser on a image, a extern application is launched to display the image.

Currently crashing almost all applications , e.g. App 'Gallery', 'Google Fotos' ...
Find the reason and fix it

**Comment by audax** [comment]
We have to put the file into the local cache, so the receiving app does not have to wait for the download.

**Comment by dannywerner** [comment]
ok, but not all files are in the cache... e.g. the file is uploaded from other client

**Comment by audax** [comment]
What I mean is:  We should first download the file and then call the intent to open it, not the other way around. To first download it we can just retrieve it with the BoxProvider which puts the file into the cache from where it can quickly be received.

Applications should expect to wait a while before they receive the file from a DocumentProvider, but currently many applications fail to do so.
