### ISSUE TITLE
Define android notification ui and features until uploading

### ISSUE THREAD

**Issue by dannywerner** [Qabel/qabel-android#198]
the app showing a simple notification until uploading files. discuss important feature / usability / ui design and implement this.
e.g. 
- group notification if user uploading several files.
- set action for click on notification (e.g. open qabel app)
- define action if notification display a upload error
- think about other notification types

**Comment by audax** [comment]
Currently assigned:

* Group notifications for multiple uploads (there currently is no way to have multiple downloads anyway)
* Clicking on a notification should just open the file browser
* check with @mr-gosh how errors should be handled

**Comment by dannywerner** [comment]
extern transfermanager to public download/upload progress
content-length is now supported in server response from block-server

**Comment by L-Henke** [comment]
Implemented in #241 
* Upload notification now shows the number of files remaining
* FilesFragment should now show pending uploads correctly
* MainActivity is launched if notification is clicked.

Missing:
* Error messages

**Comment by L-Henke** [comment]
From @mr-gosh:

> it feels wrong that a persistent notification appears on a "file open" like in the image viewer
during download and decryption its totally ok, but after the image / file is opened in the designated / internal viewer the "file download complete" notification should disappear. 
the actual behaviour is completely right for the "download file" action.

**Comment by L-Henke** [comment]
@mr-gosh I actually don't think that we can easily determine whether the external application (or even picasso as the internal image viewer) has opened the image. I would probably easier to simple remove all download notifications after a certain timeout. Would that be acceptable?

**Comment by dannywerner** [comment]
maybe notification should auto remove if user click on one? item

**Comment by mr-gosh** [comment]
@L-Henke we could try to let the "picasso" get notified about the notification id and let it on close discard the notification with this is.

**Comment by jmt85** [comment]
how is the state of this issue?

**Comment by dannywerner** [comment]
pls see nightly build. imho is all done except the progress of transfer

**Comment by jmt85** [comment]
@audax can u confirm this?
