### ISSUE TITLE
Qabel core dont running on Lenovo tablet, android 4.4.2

### ISSUE THREAD

**Issue by dannywerner** [Qabel/qabel-android#199]
On lenovo tablet the app don't running... bytecode problem in cable core. this can touch other phones.... 
test device: LENOVO lenovo B8000-F

[adblog.txt](https://files.zenhub.io/56a7490c3d6b6f7453a22855)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by audax** [comment]
Probably because we do not supply a native libcurve25519 for that architecture.

**Comment by dannywerner** [comment]
... its looks like a compiler settings for libcable..
