### ISSUE TITLE
Use prefixes provided by the accounting server

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#209]
Given a user with a box account
when a the user creates a new identity
then a new prefix should be created on the accounting server
and the prefix should be used for the volume stored in the identity object.

Given a user with a box account
when the user imports an identity
then the prefix stored in the identity should be used for the volume.

Given a user with a box account
when the imports an identity
and the prefix in the identity is not valid according to the accounting server
then a new prefix should be created on the accounting server
and a notification should be shown with an error message
and the new prefix should be used for the volume and stored in the identity.

**Comment by audax** [comment]
https://qabel.github.io/docs/Qabel-Protocol-Box/

On the accounting server:
```
Prefix

The prefix resource controls all prefixes of the user.

Create a new prefix:

    Resource: /api/v0/prefix
    Method: POST
    Request data: None
    Response data: STR

Get a list of available prefixes

    Resource: /api/v0/prefix
    Method: GET
    Request data: None
    Response data: [STR]
```

**Comment by dannywerner** [comment]
replace  HARDCODED_ROOT with identity on all places of app
Uri uploadUri = DocumentsContract.buildDocumentUri(
               BoxProvider.AUTHORITY, keyIdentifier + HARDCODED_ROOT + targetFolder + displayName);

move all source code places to one separate place (e.g QabelUriBuilder....)
