### ISSUE TITLE
Edit files mostly dont work with external apps

### ISSUE THREAD

**Issue by hash13** [Qabel/qabel-android#213]
if user want to edit files, external apps dont save (crash of external apps or message'files can't saved')

update: currently, no more files can more edit. this is a other issue and independences from first line (save from other)

**Comment by dannywerner** [comment]
maybe we can found important infos at:
http://www.grokkingandroid.com/handling-binary-data-with-contentproviders/

**Comment by dannywerner** [comment]
disable edit function in file browser or search a solution

**Comment by wischweh** [comment]
which external apps do crash? All?

**Comment by jmt85** [comment]
how we want to proceed this issue

**Comment by audax** [comment]
The edit intent is mostly used for editing images. That intent can be startet from the image viewer, so we can just remove the edit intent from the bottom sheet.

**Comment by thechauffeur** [comment]
The predicted amount of work does not really fit to the last comment here "just remove the edit intent from the bottom sheet". So an update would be nice.

**Comment by thechauffeur** [comment]
We just remove the edit intent from the bottom sheet.
