### ISSUE TITLE
Mockup for the ImageViewer

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#217]
When a user opens an image from the internal file browser
then the ImageViewer is started and a loading-spinner spins
until the image is loaded.
We need a nicer image for that spinner, it currently is the Qabel logo.

We also need a design for the 2 buttons "Edit" and "Open".

See #212 for the current implementation.

**Comment by mr-gosh** [comment]
![imageviewer](https://cloud.githubusercontent.com/assets/3028703/13144760/c6d9f4f6-d64c-11e5-8745-2c8257f3f927.png)

**Comment by mr-gosh** [comment]
can't you just add a bigger circular download progress bar that ends after download of the whole image in an open animation like in the above link?
http://www.raywenderlich.com/94302/implement-circular-image-loader-animation-cashapelayer

**Comment by audax** [comment]
Is that reasonable, @dannywerner?

**Comment by dannywerner** [comment]
yes, maybe we should move this ticket in backlog until pr to redesign the imageviewer @audax

**Comment by dannywerner** [comment]
a special circle animation is reasonable but a time costly part. iam implemented the same as filebrowser loading
