### ISSUE TITLE
Final Sentences for the Splash Screen

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-android#220]
for the Splash-screen from #151 the final sentences should be implemented:

ENG:
Do not trust us...
...it is not necessary.

DEU:
Vertrauen Sie uns nicht...
...es ist nicht nötig.

**Comment by dannywerner** [comment]
@mr-gosh das g. bei nöti habe ich mit hinzugefügt

**Comment by mr-gosh** [comment]
nagut... :P

**Comment by jasinai** [comment]
The internal ticket says, that the right wording is:
"Please do not trust us. It is not necessary.
Bitte vertrauen Sie uns nicht. Es ist nicht nötig."
@dannywerner Can you update your PR?

**Comment by jasinai** [comment]
Closed with #222
