### ISSUE TITLE
Add tell-a-friend and support 

### ISSUE THREAD

**Issue by dannywerner** [Qabel/qabel-android#226]
- We need a menu entry with function for tell-a-friend:
the user click on this item, the phone show a list of share apps (whatsapp, email).... and can share invitation to qabel app.
the text contain a link to a defined url of qabel webpage

- support:
the user should have the change to contact the qabel support
he click on the support menu item. after this, you can select the category of this:

'technicial problem'
'suggestion'
'question'

after this, he can select your favorite email client to send infos to a defined support email address of qabel.

the text  contain the phone model and version number. the user have the change to edit or remove this data.

**Comment by dannywerner** [comment]
@audax: define support email address and url for sharing

**Comment by audax** [comment]
url for sharing: the playstore link to the application

email addresses:
android-support@qabel.de
The topic of the mail should include either [Technical Problem], [Suggestion] or [Question].

**Comment by dannywerner** [comment]
this features are result of meeting 'appmarketing'

**Comment by dannywerner** [comment]
what is with the contact support features (hockeyapp) in the app? need we really two different contact features?
pls define sharing headline, text and url

**Comment by jmt85** [comment]
> 1: pls define sharing headline, text and url in both languages

EN
- You’ve been invited to join Qabel.
- For the moment this gives you the opportunity to use Qabel Box. Qabel
 Box is an end-to-end encrypted online data storage. It does not only
 enable you to store data end-to-end encrypted online, but also to share
 this data freely and end-to-end encrypted with others. Moreover Qabel
 obfuscates most of the accumulated metadata.
 Qabel is constantly expanding. So it will be possible for you in the
 future to end-to-end encrypt all your digital communication with the
 easy to use platform Qabel across applications.
 Become a part of the Qabel ecosystem and start now:
 https://qabel.de/en/qabelnow
 For more information visit at https://qabel.de/en


DE
- Sie wurden zu Qabel eingeladen 
- Damit haben Sie zunächst die Möglichkeit, Qabel Box zu nutzen. Qabel Box
 ist ein Ende-zu-Ende verschlüsselter Onlinespeicher, der Ihnen nicht nur
 die Möglichkeit bietet, Daten verschlüsselt online zu speichern, sondern
 diese auch nach Belieben mit anderen zu teilen — und das ebenfalls
 Ende-zu-Ende verschlüsselt. Darüber hinaus verschleiert Qabel auch einen
 großen Teil der anfallenden Metadaten. 
 Qabel wird ständig erweitert. So wird es Ihnen künftig möglich sein,
 Ihre gesamte digitale Kommunikation über die Qabel-Plattform
 anwendungsübergreifend und vor allem einfach und immer Ende-zu-Ende zu
 verschlüsseln. 
 Werden Sie Teil des Qabel-Ökosystems und legen Sie gleich los:
 https://qabel.de/de/qabelnow
 Mehr Infos finden Sie unter https://qabel.de

> 2: what is with the contact support features (hockeyapp) in the app? need we really two different contact features (hockeyapp and this via email)?

- we only need hockey app, the feature can be canceled
