### ISSUE TITLE
Prepaire app for release / configurate and check proguard/minify

### ISSUE THREAD

**Issue by dannywerner** [Qabel/qabel-android#227]
Until export of release version, we need to configurate proguard to get features like file shrinker, optimizer, obfuscator, and preverifier to reduce file apk size and remove unused class and method.

addition setup proguard to remove logentrys

**Comment by dannywerner** [comment]
check if we declaired permissions that we dont needed and all other issues listened in:
http://developer.android.com/tools/publishing/preparing.html

**Comment by jmt85** [comment]
i think this is your turn, too
