### ISSUE TITLE
fix junit tests to run all tests with spoon runner

### ISSUE THREAD

**Issue by hash13** [Qabel/qabel-android#229]
currently, the ui tests don't run if junit tests called before. maye the junit tests create a mock provider that conflicts with real provider on ui tests.
we want to run all tests with spoon runner to get one html report for all tests.
please evaluate what is going run and setup spoonrunner to call all tests onetime

**Comment by dannywerner** [comment]
comment out the line    
instrumentationArgs = ["package=de.qabel.qabelbox.ui"] 
in qabelbox.gradle

run all tests with
adb unstinstall de.qabel.qabel.debug
gradlew spoon

the mix of ui tests and junit tests generate errors.

if iam deactivate the follow class they worked:

BoxProviderTest
MockBoxProvider
LocalQabelServiceTest
LocalQabelServiceTester

the mock objects manipulate the database  (e.g. removes database and other that hold the service).

**Comment by dannywerner** [comment]
BoxProviderTests needs very long and can hang up. some tests in this class have a sleep with
Thread.sleep(10000l);
try to add alternative way to wait until

**Comment by dannywerner** [comment]
MockBoxProvider->MockedLocalQabelService->initAndroidPersistence
maybe this destroy some features

or

LocalQabelServiceTest-> setUp()
{
getContext().deleteDatabase(LocalQabelServiceTester.DB_NAME);
the db_ name is the same name as the real service
}

**Comment by dannywerner** [comment]
ceck if mock classes restore all states in tear down
after the mock objects running, iam get error in uitests e.g.
service.addIdenity(i1)
service.getIdentity(i1) -> database error in adb log, test failed
