### ISSUE TITLE
Show notification for new messages

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#24]

**Comment by dannywerner** [comment]
show icon in contact list if contact sended a message

**Comment by jmt85** [comment]
see #309 for more infos

**Comment by dannywerner** [comment]
same parts implemented, but not testet. see contactfragment and contactchatfragment

**Comment by dannywerner** [comment]
polling is not implemented and should in implemented in other tasks

**Comment by jmt85** [comment]
why is polling not implemented , how comes the information on the Device?
please explain to me?

**Comment by dannywerner** [comment]
no auto polling. the use must click on navigation drawer and on contact list or at a item in contactlist. only at this place, the list is refreshing (or the user click on refresh button). 

auto polling should implemented in other task and must specifiy many things....

e.g. when polling (e.g. what is when app is in background, foreground, user in contact list, user have no identitys, account is not confirmed and ... 
or what should displayed, a android notification, or only in app, only in sidemenu ....

pls dont forget that user must pay for data traffic like gprs and is not the same as desktop

before we can implement autopolling we should done the follow ticket
https://github.com/Qabel/qabel-android/issues/272

**Comment by dannywerner** [comment]
pollin is implemented
auto polling not
