### ISSUE TITLE
notification icon is missing

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-android#243]
in notifications and possibly also in toast-messages are no icons displayed...

**Comment by L-Henke** [comment]
Notification icon is already included in #241 (icon might be replaced with a better one)

AFAIK the icon on toast messages is not an vanilla Android feature, but included by CM (but I might be wrong in this point).

**Comment by dannywerner** [comment]
https://github.com/Qabel/qabel-android/issues/198

**Comment by mr-gosh** [comment]
which dimensions do you need to get a propper replacement by me?

**Comment by L-Henke** [comment]
IMHO #241 should have added this missing icons.

**Comment by jmt85** [comment]
the icons are broken, please fix @L-Henke

**Comment by jmt85** [comment]
see #24
