### ISSUE TITLE
review ui of app

### ISSUE THREAD

**Issue by dannywerner** [Qabel/qabel-android#257]
check if all drawable (icons, graphics, logo, appicon, notification) matches with the mockup or acceptable für pr

**Comment by dannywerner** [comment]
the best time for review is after we finish all ui depends features like welcome screen, help, licenses, chat ...

**Comment by mr-gosh** [comment]
Leave open until UI can be checked (wasn't possible until now)

**Comment by mr-gosh** [comment]
all ui thngs are submitted in tickets
