### ISSUE TITLE
Hardening for rough conditions / Improvement in Lifecycle and Fragment management

### ISSUE THREAD

**Issue by wischweh** [Qabel/qabel-android#261]
Putting the TestDevices in more defensive conditions revealed some Bugs (which are already fixed).
However there might still be hidden bugs related to Lifecycle Management. Keep in mind, that it is uncertain at which time the service is connected.

Please use the following configuration on your test devices:
- strictModeEnabled: true
- Always kill activities: true

At the moment the Activities don't store/restore their states using a proper bundle.
Fragments shouldn't be stored in fields of the activities, instead the FragmentManager and Tags should be used to manage fragments.
consider using https://github.com/frankiesardo/icepick for managing the savedInstanceState bundles

**Comment by wischweh** [comment]
services need to be rebound and restored on resume or another mechanism hast to be used. i.e. ContactFragment crashes if resumed (after it has been killed)

**Comment by audax** [comment]
The crashes mostly happen because fragments want to use the LocalQabelService static instance from the Application which is at that point a null pointer. The most important first step is to remove all all static references to the LocalQabelService.

**Comment by thechauffeur** [comment]
I want to talk about this. What is the gain? Is the issue name still fit?

**Comment by thechauffeur** [comment]
The gain is less app crashes.
