### ISSUE TITLE
Improve separation of buisness logic and ui by following MVVP

### ISSUE THREAD

**Issue by wischweh** [Qabel/qabel-android#262]
For improving the separation of business and ui logic i suggest to follow the MVVM as described here:
https://labs.ribot.co.uk/approaching-android-with-mvvm-8ceec02d5442#.4yittwuyh
(using the databinding library is optional but nice to have).
This should improve:
- better/clearer handling of Threading
- more explicit separation of business and ui logic (improves maintainability)
- better testability, due to separation -> business logic can be covered by unit tests.

**Comment by JoGir** [comment]
resolved. We use MVP...
