### ISSUE TITLE
Import/Export moved to Qabel-Core

### ISSUE THREAD

**Issue by hash13** [Qabel/qabel-android#269]
ContactImportExport and IdentityImportExport moved to qabel core to avoid conflicts until transfer to other platform.

- remove ContactImportExport and IdentityImportExport and test cases from android code
- update qabelcore.jar lib

**Comment by jmt85** [comment]
this is finish, right?

**Comment by dannywerner** [comment]
no. currently, the qabel core don't compiled successfully on my pc

**Comment by jmt85** [comment]
how is the status
