### ISSUE TITLE
create nine patch assets for chat 

### ISSUE THREAD

**Issue by dannywerner** [Qabel/qabel-android#271]
iam need nine patch graphics for the chat message (background for incomming and outgoing) for all 4 resolutions:

hdpi (480x800)
xhdpi (720x1280)
xxhdpi (full hd, 1920x1080)
xxhdpi (quad hd, 2540x1440)

pls assign the ticket back to me when you  are done

**Comment by mr-gosh** [comment]
this should be it...
[text-bubble-9-patches.zip](https://github.com/Qabel/qabel-android/files/146942/text-bubble-9-patches.zip)

**Comment by mr-gosh** [comment]
but later we will create these bubbles ourselfs to be able to colour them...
