### ISSUE TITLE
Drop: use sinceDate/etag from server

### ISSUE THREAD

**Issue by hash13** [Qabel/qabel-android#272]
same issue as desktop
https://github.com/qabel/qabel-desktop/issues/154

**Comment by dannywerner** [comment]
currently, we load all messages from timestamp 0
see ChatServer.refreshList

**Comment by jmt85** [comment]
optinal if it easy to fiy, do it

**Comment by wischweh** [comment]
we need a fiel like long lastModifiedSince in HTTPResult to be able to implement this

**Comment by jmt85** [comment]
why should not you do that?

**Comment by dannywerner** [comment]
can be implemented as soon as Qabel/qabel-core#472 is merged

**Comment by jmt85** [comment]
is merged

**Comment by dannywerner** [comment]
@audax is the new version with the merge live?

**Comment by julianseeger** [comment]
core "live" is what every you integrate as a jar...

concerning the drop-server:
https://github.com/Qabel/qabel-drop/pull/44 doesn't look merged and is probably not what it will look like after a review.

You can integrate the new core anyways. It should provide the lastModified() method with null or similar until the drop server provides a last-modified header in the response. Imho the clients should behave "reasonable" in such situations

**Comment by julianseeger** [comment]
Qabel/qabel-drop#44 is merged now. This can be implemented with a test drop-server that is on current qabel-drop/master

**Comment by jmt85** [comment]
how is the status?

**Comment by audax** [comment]
Still the same, it is not implemented.

**Comment by julianseeger** [comment]
If we're not in a hurry with this (without frequent polling and with reasonable device clocks, it may not hurt that much) we could save time by skipping this feature and go straight to etags & push

**Comment by enkore** [comment]
Since qabel-drop#45 really doesn't take long (if I got it right, that is) I just quickly implemented it: https://github.com/Qabel/qabel-drop/pull/59 may be useful for @jogir?

**Comment by enkore** [comment]
Qabel/qabel-drop#59 is done and also documented at http://qabel.github.io/docs/Qabel-Protocol-Drop/#communication-with-server
