### ISSUE TITLE
Update app name and package

### ISSUE THREAD

**Issue by dannywerner** [Qabel/qabel-android#276]
The app should renamed from QabelBox to "Qabel".

- change app name in manifest
- check all strings 
- BoxAccount should rename to "Qabel Account"

The app package should changed from de.qabel.qabelbox to de.qabel.android. Be carefully when your rename the package to avoid a big merge issue. maybe it can be enough, if we rename only the package id in manifest

**Comment by dannywerner** [comment]
maybe your can repackage classes woth proguard
remove all log.v and log.d from code (with proguard, or with gradle until export, or with unix files tools or add own log class like MyLog.d|v|e|w and change all Log.d to this class. so you able to change log level)

**Comment by audax** [comment]
Can't we just change the log config?

**Comment by JoGir** [comment]
AppName is allready Qabel and BoxAccount is allready labeled as Qabel Account

**Comment by audax** [comment]
And ApplicationID was changed.
