### ISSUE TITLE
contact list does not update automatically

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-android#297]
when I import a contact via file directly and then press refresh to update the contact, the contact is gone. When i import the contact again, i get the message that the contact is still in list. Change menu and return makes it back intact .

see https://rink.hockeyapp.net/manage/apps/280963/feedback/444547 point 2

**Comment by dannywerner** [comment]
pls check in mainactivity if we have multiple instances of contactfragment...this is maybe a fast solution
