### ISSUE TITLE
two view on a screen

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-android#298]
- start App
- Switch to the contacts by wiping from left to right
- Selecting a contact
- Change back to the contacts 

![137378](https://cloud.githubusercontent.com/assets/4853105/13502285/9f6e6bda-e16a-11e5-94e4-99339092da3d.png)

**Comment by mr-gosh** [comment]
isn't really design related...

**Comment by dannywerner** [comment]
pls check fragment creation prozess (fragmentmanager.replace/add).... maybe in contactfragment.... and the background settings in layout

**Comment by jmt85** [comment]
invalid bug? ticket not close till we are sure

**Comment by mr-gosh** [comment]
confirmed!
