### ISSUE TITLE
superfluously line at chatting Layout

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-android#302]
every send message has a small line at the right side.
![136703](https://cloud.githubusercontent.com/assets/4853105/13523344/2e67a484-e1f5-11e5-901d-8bffc65e8f80.png)

**Comment by mr-gosh** [comment]
these are not visible in the exported 9-patches - so this must happen later (if this is in the graphic)

**Comment by L-Henke** [comment]
Can't be reproduced with other devices and device of the bug reporter with current master.
