### ISSUE TITLE
Sidebar menu icon change 

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-android#306]
all three icons must be changed
kontakte = multi contact icon
datein = folder icon
einstellungen = gear icon

![sidebar](https://cloud.githubusercontent.com/assets/4853105/13527340/a8e4e1b8-e20e-11e5-91fb-c3fafb1824ed.jpeg)

**Comment by mr-gosh** [comment]
I can't upload .svg's here - so these links could help:

https://materialdesignicons.com/icon/account-multiple
https://materialdesignicons.com/icon/folder
https://materialdesignicons.com/icon/settings
