### ISSUE TITLE
Sidebar icons wrong

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-android#307]
identity icon wrong
use letter avatar from creation wizard instead...

![137723](https://cloud.githubusercontent.com/assets/4853105/13527652/ee83a36a-e210-11e5-8bc0-9fb7b24dd5d5.jpeg)
![137724](https://cloud.githubusercontent.com/assets/4853105/13527654/f028469e-e210-11e5-8bd9-976ef18ca151.jpeg)

**Comment by L-Henke** [comment]
The Android DrawerLayout only shows grey outlines of menu icons. This is specified in the [Material Design Patterns](https://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-specs) (```Icon values: 54% #000000```) and no other mode is supported by the library. So if we add our generated icons, we will only see a grey circle. If we would want to show the initials as outlines in the circle, we would have to find a way to cut the letters out of the circle (making these areas transparent) which I think would be way to much work for a little icon. But you @jmt85 would have tell your opinion on this.

**Comment by mr-gosh** [comment]
ok - than we wait with the integration of the avatar until we can add this to the top bar (like proposed by material design) and until than we replace the icon by the not outlined icon: https://materialdesignicons.com/icon/account

**Comment by audax** [comment]
Fixed since we introduced the new drawer
