### ISSUE TITLE
New things happened indicator

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-android#309]
we need to poll from time to time for new things (shares, messages and co.) and need to inform the user on these things.

should i mockup a "unread new messages" badge or something similar, or won't this get into beta?

**Comment by jmt85** [comment]
for android it is a litte bit tricky, we decide it on monday

**Comment by mr-gosh** [comment]
Possibly in combination with an offline indicator...

**Comment by mr-gosh** [comment]
Could be one like this:

![sidebar](https://cloud.githubusercontent.com/assets/3028703/13547743/4eca912a-e2de-11e5-8f6f-7108455663a6.png)

**Comment by jmt85** [comment]
please add a config for the polling time. The add the intervall after i talk to ow

**Comment by dannywerner** [comment]
1. at which time should polling running?

when app is in foreground?
when app is in background?
when app is not started, e.g. after rebooting the device?
when user is on every screen of the app or not on all?

2. what should happens when new messages received?

show in sidemenu of appliation?
show a toast or dialog in app?
show a android notification in notificationbar?

if user can't disable autopollin it can get some negative ratings.... not all users have a data plan and must pay per time or per mb for data transfer. frequency auto pollin increase the battery consumption and we currently pollin all messages from timestamp 0.

**Comment by jmt85** [comment]
thank you that you've made ​​so many thoughts

> when app is in foreground?

- yes

> when app is in background?

- yes

> when app is not started, e.g. after rebooting the device?

- yes

> when user is on every screen of the app or not on all?

- on every screen 

> show in sidemenu of appliation?

- yes

> show a toast or dialog in app?

- yes

> show a android notification in notificationbar?

- yes

> should user have chance to disable auto polling?

- yes, time intervall comes today, probably from 10 sek - 10 min and disable

> frequency auto pollin increase the battery consumption and we currently pollin all messages from timestamp 0.

- it is depented from ##272, but you can still start to work.

**Comment by dannywerner** [comment]
- should device polll for new messages if display is off?
- should the android notification in notification bar start a default audio signal and/or vibration if new message recevied?
see http://developer.android.com/reference/android/app/Notification.html#DEFAULT_SOUND

**Comment by jmt85** [comment]
> should device polll for new messages if display is off?

- yes

> should the android notification in notification bar start a default audio signal and/or vibration if new message recevied?

- yes, both

**Comment by mr-gosh** [comment]
Can the polling interval be different on some situations?
Else it will eat the battery!

For example - if display is of - possibly all 15 min. Should be enough (until the chat really is usable)

**Comment by audax** [comment]
Yes it can, esp. if we use a SyncAdapter with which the Android system will queue up all sync requests to save battery. In the current implementation, it is not an instant messenger by any means. We'd need something like GCM for that, which would a change we have to discuss first.

**Comment by hash13** [comment]
maybe this can help you?
https://developers.google.com/cloud-messaging/network-manager
https://developers.google.com/android/reference/com/google/android/gms/gcm/PeriodicTask
https://developers.google.com/android/reference/com/google/android/gms/gcm/OneoffTask

**Comment by audax** [comment]
Ops, I forgot to actually add the badges to the sidebar.

It shouldn't have been in the same issue anyway…

**Comment by audax** [comment]
and a new PR for the badges is fine.

**Comment by audax** [comment]
I'll create another PR for the remaining tasks:

* Badge with the number of unread messages
* Audio signal and vibration for new notifications
* Show a toast in the application for each notification (Is that really a good idea?) @jmt85 
* Configure polling interval and disabling it

**Comment by mr-gosh** [comment]
For the first unread messagr there is a detailed message after thst these are  up as explained in the material design guidelines...

Messages are also only counted for real decryptable messages but this is obvious i hope

**Comment by audax** [comment]
The notifications were implement in #523.

If the user is in a conversation fragment with the contact, no notification is shown, the chat is just updated. If the user is in the contact list of the identity that received a message, no notification is shown.

In all other cases one notification per identity is shown, as explained in the material design guidelines. Clicking on a notification for messages from a sinlge contact opens a chat window. Clicking on a notification for a group of messages from different conacts opens the contact list.

**Comment by audax** [comment]
After discussing it further the missing feature set was reduced to:

* Badge with the number of unread messages
* Vibration for new messages

**Comment by audax** [comment]
I'll put the badge with the number of new things on the burger:
![badge](https://i.stack.imgur.com/sdJLZ.png)

Please update the mockups @mr-gosh

**Comment by mr-gosh** [comment]
I'll do that 
Good idea btw.

**Comment by audax** [comment]
Maybe not, that is way harder than I thought. The whole badge stuff is way harder than I thought.

The solution I found is to implement another drawer library: https://mikepenz.github.io/MaterialDrawer/
Can you work with that?

**Comment by mr-gosh** [comment]
If this doesn't auto import a buttload of google dependencies i am fine with that... 
Btw. there is mentioned the usage of svg icons... You know what i mean ;-)
