### ISSUE TITLE
Contact delete missing variable

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-android#310]
When a contact is deleted, thwre is the name-variable not filled

**Comment by JoGir** [comment]
i think i fixed this is in #297

**Comment by mr-gosh** [comment]
if not - here is the screenshot
![e13b4a19-36ab-4132-b7d4-76d22b4aac56](https://cloud.githubusercontent.com/assets/3028703/13547513/969db34a-e2d6-11e5-9d8f-aeee303b9fd2.jpg)

**Comment by audax** [comment]
That one is fixed
