### ISSUE TITLE
Offline Indicator

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-android#313]
as mentioned in #309 there should be an offline indicator, that shows to the user, that at the moment only cashed things are available.
Suggestions welcome (could also be realised in the lower right corner of the menue, but here it fitted the best in my tests:
a Mockup and a graphic for that stuff:

![offline-badge_512](https://cloud.githubusercontent.com/assets/3028703/13547838/8436611a-e2e1-11e5-8273-8c490ad62be5.png)
![sidebar-offline](https://cloud.githubusercontent.com/assets/3028703/13547837/7eb36c56-e2e1-11e5-817f-6c94831b775b.png)

**Comment by mr-gosh** [comment]
@jmt85 i talked with @julianseeger about this ticket regarding the desktop and we should choose the same solution in both clients.
So the fullscreen "nagscreen" indicating nothing possible without connection should be implemented in android too.

**Comment by julianseeger** [comment]
![offline-indicator](https://cloud.githubusercontent.com/assets/3258762/13601924/bcc486a2-e533-11e5-9032-caf8a3cba7e9.png)
