### ISSUE TITLE
Qabel Icon in Startscreen with wrong Dimensions

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-android#316]
The Qabel Icon has wrong Dimensions (is a bit compressed) in the startupscreen:

![startscreen-bug](https://cloud.githubusercontent.com/assets/3028703/13572140/ea1f197a-e478-11e5-817f-93ab24169a83.png)

![qabel_logo_icon font_orange](https://cloud.githubusercontent.com/assets/3028703/13572123/d4e452fa-e478-11e5-834a-8bff75901b12.png)

[qabel_logo_icon+font_orange.svg.zip](https://github.com/Qabel/qabel-android/files/161450/qabel_logo_icon.font_orange.svg.zip)

**Comment by mr-gosh** [comment]
same in #334

**Comment by L-Henke** [comment]
I can't reproduce this bug. This is what it looks like on my device. @mr-gosh can you please check if the layout is still broken on your device?
![Screenshot_20160310-113448.png](https://files.zenhub.io/56e14e76ff575723435b888a)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by L-Henke** [comment]
If the provided png has the wrong aspect ration, I would need a set of png's with the correct ratio.

**Comment by L-Henke** [comment]
@mr-gosh I tried to create the .png set from your provides .svg, but the orange is slightly wrong. Would you mind to create an .svg (or even the .png set) with the correct color?

**Comment by audax** [comment]
Indeed, colors are off when I export the SVG.

**Comment by audax** [comment]
Please send me a PNG with a width of 557 @mr-gosh

**Comment by mr-gosh** [comment]
changed color and resolution

![qabel_logo_icon_font_orange_557x878](https://cloud.githubusercontent.com/assets/3028703/13701746/3ae50f72-e78a-11e5-84d3-b5a682be409a.png)
