### ISSUE TITLE
Create Account Logo wrong dimension

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-android#334]
In the Create Account View - the Qabel Logo has wrong Dimensions and lacks resolution:

![create-account-logo-bug](https://cloud.githubusercontent.com/assets/3028703/13666086/01dae7c2-e6b0-11e5-96e4-3b171f99f4be.png)

please replace with logo from #316

**Comment by audax** [comment]
Please send me PNG with a width of 488 @mr-gosh

**Comment by mr-gosh** [comment]
![orange-icon_488x769](https://cloud.githubusercontent.com/assets/3028703/13701650/a5bb735a-e789-11e5-8c82-60cc57622676.png)
