### ISSUE TITLE
Welcome Screens need the right Texts

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-android#337]
here are the screens for the Welcome Screens with the right texts (EN & DE)

![welcome_screens_v0 3](https://cloud.githubusercontent.com/assets/3028703/13678744/8c77687a-e6f0-11e5-9ed9-64e3c57822fb.png)

**Comment by JoGir** [comment]
Still not nice. I am working on this.

**Comment by JoGir** [comment]
Master
![licence_current](https://cloud.githubusercontent.com/assets/16522130/13705661/12ea01c2-e7a2-11e5-93b5-5aafc49a41c8.png)
![welcome_1_current](https://cloud.githubusercontent.com/assets/16522130/13705662/1309b9d6-e7a2-11e5-962a-ad462358d4df.png)

Current
![licence_improved](https://cloud.githubusercontent.com/assets/16522130/13705675/23544f9a-e7a2-11e5-9560-1ec285638b43.png)
![welcome_1_improved](https://cloud.githubusercontent.com/assets/16522130/13705674/234df604-e7a2-11e5-94d6-5a59db54ef56.png)

**Comment by mr-gosh** [comment]
In English version the linebreaks are missing in the first two welcome screens

**Comment by audax** [comment]
now fixed.
