### ISSUE TITLE
Manually import a contact

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#34]
From a (json) file which contains the public key and a drop address (maybe additional information)

**Comment by thechauffeur** [comment]
And manually adding a contact.

**Comment by audax** [comment]
I'll try my best:

Given a user in the contact list fragment
when the users clicks the add button
then he can click "import contact"
and import a .json file with contacts
and the contact appears in the contact list

Given a user in the contact list fragment
when the users clicks the add button
then he can click "manually add contact"
and enter an alias, dropurl and public key
and the contact appears in the contact list

**Comment by dannywerner** [comment]
the app can now add contact via:
import from json file
qrcode
manually input.
after added a contact, the contact ist not refreshed. would fixed with #36. until this, to refresh contact list click on files, (via drawer) and after on contact.
