### ISSUE TITLE
Add thanks list to About Screen

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-android#357]
in the last "About Screen" Mockups there is a Button that shows a list of People we wanna thank.
I don't want to post the list here...
Who will need that list, so I can send it over?
Else - it in Redmine Ticket#4323... ;-)

**Comment by mr-gosh** [comment]
![about_dialog](https://cloud.githubusercontent.com/assets/3028703/13728201/5db87f2a-e910-11e5-9fb1-b64c18ec92f4.png)

**Comment by audax** [comment]
Implemented.
