### ISSUE TITLE
Better communication of BETA state of the App

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-android#358]
E.g. in the welcome screens. Something like a nice and shiny "BETA" tag somewhere :)

@mr-gosh please think about a good place for that. Keep in mind that it would help if it's implementation is less time consuming ;)

This should be considered important -- let's ship this fix with one of the next hotfix updates if possible.

**Comment by mr-gosh** [comment]
#266

**Comment by dannywerner** [comment]
no place for additional badge. 
@mr-gosh is creating a new fork us badge with beta information

**Comment by mr-gosh** [comment]
![github-beta-badge](https://cloud.githubusercontent.com/assets/3028703/13746716/ea8f98e0-e9f4-11e5-8620-47af150bc7c4.png)
