### ISSUE TITLE
Export contacts

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#359]
Given a user with a contact in the contacts activity
When he long clicks on the contact
And selects "Export to a file"
And selects a folder and file name
Then the contact is saved into the file

Given a sure with multiple contacts in the contacts activity
When he presses the menu button
And selects "Export all contacts to file"
And selects a folder and file name
Then all contacts are saved into the file

**Comment by dannywerner** [comment]
can be closed?

**Comment by audax** [comment]
Yes, the follow up issue is already created.
