### ISSUE TITLE
Contact list

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#36]
Redesign the contact list, it should look like in the mock ups.

Provided functions in the contact list:
* [x] Import contacts #35  #34 
* [x] Export contacts (should already have a backend)
* [x] Remove contacts

**Comment by dannywerner** [comment]
add auto refresh after contact added or deleted

**Comment by dannywerner** [comment]
tasks: 
- delete contact
- auto refresh after delete or import/create new contact
- redesign ui
