### ISSUE TITLE
chat partner dont display

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-android#384]
you can't see who you're talking to.
change "chat" to the name of the contact you are talking to according to the mockups.
And add the ~~gravatar~~ avatar to the chat.

![137756](https://cloud.githubusercontent.com/assets/4853105/13779720/c01f208a-eabc-11e5-9d9c-59f7cbae435b.jpeg)

**Comment by audax** [comment]
Really a [https://secure.gravatar.com/](gravatar)? This would leak a ton of metadata.

**Comment by mr-gosh** [comment]
Of course not - an avatar is fine but not an external service - i suppose this was a typo

**Comment by JoGir** [comment]
fixed in #401
