### ISSUE TITLE
sharing menu icons and text wrong

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-android#385]
change file sharing menue according to the mockup
icons, text and sepperator

![137774](https://cloud.githubusercontent.com/assets/4853105/13779785/0bb07b0c-eabd-11e5-893c-6a44d78925d1.jpeg)

**Comment by mr-gosh** [comment]
the icon "Freigeben - in qabel" needs to be reworked - the rest is final

**Comment by JoGir** [comment]
@mr-gosh The simple black QabelLogo for the "Share"- in Qabel item is missing.
Please add in #426
