### ISSUE TITLE
.qco mimetype

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-android#386]
.qco files can not be opened via the file browser. You only can open the file from Qabel

**Comment by mr-gosh** [comment]
isn't it called "mimetype"?

**Comment by audax** [comment]
Of course, and that is also the name of this ticket.

**Comment by dannywerner** [comment]
what do you mean with file browser? the file browser in the qabel app they cant open or third party file browsers?

**Comment by jmt85** [comment]
I do not mean the qabel internal file browser . I mean the native browser.

If you downloaded a contact from any source, should be given the opportunity to open it directly with qabel.
