### ISSUE TITLE
help site overlay

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-android#387]
open about -> open help 

Not all devices

reproducible Nexus 4 with 5.1.1 (Julian)

![140000](https://cloud.githubusercontent.com/assets/4853105/13780188/ac4bd0a6-eabe-11e5-85b0-fbc4ceac041d.jpeg)

**Comment by JoGir** [comment]
Can reproduce this bug with the emulator. May this is fixed in #298, pls confirm this with a real device.

**Comment by wischweh** [comment]
probably related to #261 (bad management of the backStack and fragments)

**Comment by julianseeger** [comment]
fix
