### ISSUE TITLE
logout

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-android#405]
logout function is missing

**Comment by wischweh** [comment]
I decided to place the logout button in the side menu (identity mode) right below "Manage Identities". Any objections? There shoudl be a unique icon for the entry.
![device-2016-04-05-163653](https://cloud.githubusercontent.com/assets/363339/14285855/5702b1ce-fb4d-11e5-9e15-c447efae8bdc.png)

**Comment by wischweh** [comment]
PR https://github.com/Qabel/qabel-android/pull/453 please review

**Comment by audax** [comment]
I think logout should be in the settings menu, sorry that I didn't answer that sooner.

**Comment by mr-gosh** [comment]
Icon should be this one: 
https://materialdesignicons.com/icon/account-off

**Comment by wischweh** [comment]
@mr-gosh if we move the stuff to settings, the icon is obsolete

**Comment by mr-gosh** [comment]
perhaps - also in the settings we need icons for this - but there I would change to a more technical "eject" button, but here the updated mockup:
![sidebar-identity-switcher](https://cloud.githubusercontent.com/assets/3028703/14311620/84ec540a-fbe8-11e5-915e-7f86f39fac43.png)

**Comment by julianseeger** [comment]
logout = relogin with fixed username
