### ISSUE TITLE
Font shadow rendering problem

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-android#406]
1. sometimes there are misrendered shadows - sometimes they disappear in swipe
2. in the headlines the shadows are often cut at the Ende oft the special font
3. the status bulletins are flipping around
4. the github link is Zoo small in a tablet
5. the whole tet is strange formatted on a tablet

![142134](https://cloud.githubusercontent.com/assets/4853105/13982164/a7159876-f0e8-11e5-9755-e1c6466e4b88.jpeg)

**Comment by JoGir** [comment]
1.,2. fixed shadows
3. already fixed by danny
4. changed size to fixed dp
5. who is tet? (but changed text-size to 20dp)

We should check this again on a tablet
