### ISSUE TITLE
Disable crashreporting dialog for ui tests

### ISSUE THREAD

**Issue by wischweh** [Qabel/qabel-android#407]
Sometimes ui tests fail because a previous run caused a crash and the MainActivity starts with the "send crashreport?" dialog (which blocks other actions). UI Tests should disable this behavior.

**Comment by dannywerner** [comment]
a example function is implemented. you only need to set 'send no test reports' in tests scripts

**Comment by audax** [comment]
Crash reporting is disabled in debug builds.
