### ISSUE TITLE
Link to file in chat useless

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-android#409]
after clicking on a file link in a chat it gets integrated into filebrowser. a later click should open the default action or ask for what to do...
it should open images, on other files should be asked what to do (show in filebrowser, share in qabel, share externally, etc)

![142954](https://cloud.githubusercontent.com/assets/4853105/13986926/4df9970c-f105-11e5-9d7c-f6956e64de40.jpeg)

**Comment by JoGir** [comment]
currently looks like this, but functionality is still bad...
![screenshot_2016-03-24-18-51-55](https://cloud.githubusercontent.com/assets/16522130/14026112/aaef19d6-f1f1-11e5-93cf-c09fa387fb71.png)

**Comment by jmt85** [comment]
ack

**Comment by jmt85** [comment]
please create pr
