### ISSUE TITLE
wrong item - file browser

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-android#410]
see screenshot

![141862](https://cloud.githubusercontent.com/assets/4853105/13986955/7caf20d0-f105-11e5-8726-f677851866ce.jpeg)

**Comment by dannywerner** [comment]
no mockup available
is this correct? 
if no, provide my with more informations
![screenshot_20160329-154820](https://cloud.githubusercontent.com/assets/5576400/14110232/e98ca1e0-f5c5-11e5-807b-3a0a73e1d304.png)
