### ISSUE TITLE
wrong icons - manage Identity

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-android#412]
3 paper clips for export and share
and share symbol rename

see screenshot

**Comment by dannywerner** [comment]
screenshot?

**Comment by jmt85** [comment]
sry i mean mockups

rename: pen
delete ok
both export: export icon 
share : share symbol 

![icon](https://cloud.githubusercontent.com/assets/4853105/13988089/b1661f18-f10a-11e5-9d75-8cce031ae45b.png)
