### ISSUE TITLE
data loss on DM conflict

### ISSUE THREAD

**Issue by julianseeger** [Qabel/qabel-android#421]
The `AbstractNavigation` merges only updated files when the `commit` conflicts with another DM's `commit` (like from another device). Other changes like deleted files, deleted folders or new folders are lost. (The files of deleted files are actually deleted but the DM still has their reference leading to undownloadable files).
This behavior is not only theoretical has been observed when using mobile and desktop concurrently. 

A fix for this is currently in progress for the desktop client...

**Comment by audax** [comment]
Syncing does require that all merges are applied on a conflict. Since we do not sync on android, a reasonable fix would be to just not delete the file on the server (which obviously was not intended).

**Comment by jmt85** [comment]
depended #431

**Comment by audax** [comment]
Resolved by #591 

The new code is from the core and it doesn't have that problem.
