### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by JoGir** [Qabel/qabel-android#426]
* Create a list of all Icons we currently need
* Add all Icons with correct size for different resolutions

**Comment by julianseeger** [comment]
Can't you just add the highest resolution (or a vector image) and let gradle to the resizing on build?
Haven't done it yet but taking care of it manually sounds wrong to me ;)

**Comment by dannywerner** [comment]
normaly,  the graphic artist create the drawables and send this to the developer. if not  possibility, use android studio plugins to resize the images

**Comment by audax** [comment]
Esp. we need the qabe logo in different sizes.

**Comment by mr-gosh** [comment]
the file with the used icons is ready - so i can export all icons in the desired resolutions.
question is:
do you want 100% black icons and to the 80% / 50% / 30% stuff on jour own - or do you need both?
do we need white icons at the moment too?

in the documentation referenced by @JoGir were a lot of resolutions, but I remeber, that we did not support older devices, we only need a few of these...

so:

1. which colors?
2. which demensions?

**Comment by audax** [comment]
@mr-gosh Do you have all informationen that you need?
