### ISSUE TITLE
User feedback for errors while creating folders

### ISSUE THREAD

**Issue by wischweh** [Qabel/qabel-android#436]
At the moment two edge cases while creating a folder are ignored without feedback for the user:

- User tries to create a folder which already exists
- User tries to create a folder with empty String as name.
In both cases nothing happens but the user is not aware of this.

Keep in mind: The attention span on mobile devices is very short. 
In the first case the user might not get what he expectect. Lets say he creates a new Folder: "My New Files" he might expected an empty folder. But if he already used such a folder in the past the folder might already contain content.

There are two possible strategies:
1. Preventing wrong operation by checking and giving feedback while user types.
2. Providing options/feedback in case of error. i.e. (cancel or overwrite)

**Comment by julianseeger** [comment]
close?

**Comment by thechauffeur** [comment]
I don't see why I'm the assignee here.
