### ISSUE TITLE
Sidemenu header qrcode to much blurred

### ISSUE THREAD

**Issue by hash13** [Qabel/qabel-android#445]
the image is blurred... someone have use a very small icon for the sidemenu. 

![qrcode](https://cloud.githubusercontent.com/assets/5576400/14240519/bab9d3a4-fa45-11e5-89f1-e8469b39f64e.png)

**Comment by audax** [comment]
We should show the actual QR there instead.

**Comment by mr-gosh** [comment]
Are you sure?
isn't it a privacy flaw if someone can scan you id, if you just open your sidebar?

I made a custom qr logo icon - perhaps we should display the avatar in big - and a qr icon you can tap on...?!?

**Comment by mr-gosh** [comment]
perhaps something like this:

![sidebar-alternate-arangement](https://cloud.githubusercontent.com/assets/3028703/14250944/e4d733a8-fa80-11e5-9fbf-394346d05804.png)
