### ISSUE TITLE
Contact exchange via E-Mail

### ISSUE THREAD

**Issue by jmt85** [Qabel/qabel-android#475]
There should be the possibility to send, out of the app, a contact as email to someone else.

**Comment by JoGir** [comment]
![screenshot_20160428-184830](https://cloud.githubusercontent.com/assets/16522130/14894703/3bd67608-0d75-11e6-9cd2-4ab8eae4ee5b.png)
![screenshot_20160428-184837](https://cloud.githubusercontent.com/assets/16522130/14894706/40748cb8-0d75-11e6-93f9-ecb65192d322.png)
