### ISSUE TITLE
App crash with folder name ::::

### ISSUE THREAD

**Issue by hash13** [Qabel/qabel-android#483]
create folder with name ::::44343:::::
and try to upload file in this

the app crash (arrayindexoutofbound).

the app use intern a string parser for content provider and the :::: should be a forbidden name.

resolution:
add check in create folder that the new folder name dont contain ::: or other identifier that hard coded in content resolver

check if this touch the same issue if uploading a file with ::::

**Comment by audax** [comment]
Actual requirements:

Given a user with an empty volume
when the user creates a directory "::::"
then the user can create a file in that directory

Implement a test in the DocumentIdParserTest class which validates that directory and file document ids can indeed contain the token "::::".
