### ISSUE TITLE
Replace AsyncTask with RxJava

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#527]
AyncTasks get silently killed, call their callbacks on the wrong fragment and do other bad stuff.

RxJava is nice.

**Comment by hash13** [comment]
- best practicse for android is do communicate not direct with instance of fragment or activity,
- bether is with listeners like broadcast receiver or other tools like eventbus ...

**Comment by audax** [comment]
Or like RxJava and decoupled presenter classes, yes
