### ISSUE TITLE
Integrate with Box library from core

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#543]
https://github.com/Qabel/qabel-core/pull/510

The Box library was extracted from Qabel-desktop to the core and should be used as a base for the android specific implementation.

One major difference between the implementations is that the core implementation creates new BoxNavigaton objects in navigate() where in the android implementation the navigate() method is void and mutates the object.
The second difference is the use of a TransferManager inside of the BoxNavigation object in Android instead of seperate read and write backends.

**Comment by jmt85** [comment]
see #554
