### ISSUE TITLE
First Start Wizard - Progress Indicators too big after update to 0.7

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-android#551]
during the first start wizard the progress indicator toggle boxes are too big:

![screenshot_20160608-111238](https://cloud.githubusercontent.com/assets/3028703/15889125/1ab9f0de-2d6a-11e6-9abb-274f7a7d0df9.png)

**Comment by JoGir** [comment]
@mr-gosh pls adjust the size of the drawables radiobox_marked_white and radiobox_blank_white.
Currently the icons uses our default sizes for icons 48px(hdpi) to 128px(xxxhdpi)

**Comment by jmt85** [comment]
take a look at the screenshots,

mr-gosh is currently not available
