### ISSUE TITLE
in identity-manage-view is a nonsens menue-entry

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-android#552]
in the identity-manage view is an menue entry in the top right corner menue that pop-ups a message regarding the alpha state of the app
this should be completely removed cause everything regarding this is located in the about dialog

![screenshot_20160608-111627](https://cloud.githubusercontent.com/assets/3028703/15889538/d4574a5e-2d6b-11e6-802e-603bcbeb0a09.png)

**Comment by JoGir** [comment]
Default optionsmenu is removed in #573
