### ISSUE TITLE
Image viewer not working anymore

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-android#559]
When i upload a picture and click on it to view it - it loads but onl displays a grey matte...

**Comment by mr-gosh** [comment]
![tmp_27671-screenshot_20160611-203306-1654755237](https://cloud.githubusercontent.com/assets/3028703/15997633/a139b994-3136-11e6-82dc-d125dfac1909.png)

**Comment by mr-gosh** [comment]
Verified in 0.7.1

**Comment by audax** [comment]
Does the loading spinner appear at all and may you share a picture that you can't open in the image viewer in this issue?
