### ISSUE TITLE
Strange behavior and crashes during search

### ISSUE THREAD

**Issue by hash13** [Qabel/qabel-android#584]
- Click at search icon in file browser
- Entering a search term in which no results expected (image 1) but
- See a new endless loading page (image 2)
- Click on Filter, see strange values (image 3)
- click on back to go to main, the app crashed (image 4)

![1-searchvalueentered](https://cloud.githubusercontent.com/assets/5576400/16417582/c7fa6094-3d46-11e6-9b5c-57214f4ce5f8.png) ![2-endlessloading](https://cloud.githubusercontent.com/assets/5576400/16417584/c9cc43ce-3d46-11e6-80b7-184e2c82c303.png) ![3-filteroptions](https://cloud.githubusercontent.com/assets/5576400/16417590/cc128a12-3d46-11e6-8c9b-08ae262aa4e9.png) ![4-crash](https://cloud.githubusercontent.com/assets/5576400/16417592/cd8d2352-3d46-11e6-82e8-25becbf6da09.png)

**Comment by thechauffeur** [comment]
This is deprecated.
