### ISSUE TITLE
Support for multiple identities on one device

### ISSUE THREAD

**Issue by audax** [Qabel/qabel-android#61]

**Comment by audax** [comment]
Switching between identities works, but there may be some GUI changes needed when we get updated mockups.

**Comment by L-Henke** [comment]
@audax do you think that should keep us from closing this issue for now? As it is possible to add, modify and delete identities as well as select them as the active identity.

**Comment by audax** [comment]
One part is missing: Selecting a new identity after deleting one. What happens if there is no identity left?

**Comment by mr-gosh** [comment]
if the the app isn't usable without an identity - the "add identity" should than be hovering the screen the whole time?!?

**Comment by audax** [comment]
Or we always open the add-identity fragment if we have no identity. When we implement import-identity #38 we can include this into the add-identity fragment, too.
