### ISSUE TITLE
Publish Identity to Qabel Index

### ISSUE THREAD

**Issue by mr-gosh** [Qabel/qabel-android#612]
Mockup a solution like #472 for the next release

**Comment by mr-gosh** [comment]
To have an intermediate solution for people who have created their identities prior the possibility to add metadata to the qabel-index we need a more convenient solution than to go to the idenity editor by himself and add mails or phone numbers by hand.
cause i don't have my notebook in reach here a sketch and a description to present my solution:

**New Sidebar Entry "$Avatar + Add Qabel-Index entry" + "X"**
![add-index](https://cloud.githubusercontent.com/assets/3028703/17727544/4ac5081e-645a-11e6-97b7-ea44d85ef134.jpg)
So, these "one time icons appear ONCE if an identity is detected, that has no qabel index entry attached.
So per ID one row, that is clickable with an "X" for muting this proposal.
If someone clicks the row he is directly brought to "Identity-Creator #6" and following the rest of the wizard, to be brought to the identity details view in the end.

Identity Creation Wizard part 6 and following are these:
![identity-creator-6](https://cloud.githubusercontent.com/assets/3028703/17727689/53ee1b96-645b-11e6-900e-6cbd5b2fceca.png)

![identity-creator-7](https://cloud.githubusercontent.com/assets/3028703/17727687/53ec043c-645b-11e6-8fa0-69fa35061176.png)

![identity-creator-8](https://cloud.githubusercontent.com/assets/3028703/17727688/53ed171e-645b-11e6-9839-eb9f8e286799.png)

**Comment by mr-gosh** [comment]
@thimm @thechauffeur is this self explaining enough? sorry for the sketched mockup...

**Comment by audax** [comment]
Implemented
