### ISSUE TITLE
Migration fail

### ISSUE THREAD

**Issue by JoGir** [Qabel/qabel-android#628]
* [x] Something is wrong with identities and contacts. check values for new fields.
* [ ] filesystem is broken

**Comment by audax** [comment]
https://github.com/Qabel/qabel-core/blob/master/box/src/main/java/de/qabel/box/storage/BoxVolumeImpl.kt#L88

getLong() needs to be called 2 times to extract 2 consecutive longs. The API sucks, thanks Java.
