### ISSUE TITLE
Contact - Identity Handling with Hello

### ISSUE THREAD

**Issue by JoGir** [Qabel/qabel-android#629]
What happens if a known contact has sent a message to an other identity (not assigned with the contact)

**Comment by audax** [comment]
The contact is assigned to other identity, too. The contact status is global for all identities.

**Comment by JoGir** [comment]
as currently implemented https://github.com/Qabel/qabel-core/blob/master/chat/src/main/java/de/qabel/chat/service/MainChatService.kt#L138
