### ISSUE TITLE
Receiving a shared file - workflow

### ISSUE THREAD

**Issue by JoGir** [Qabel/qabel-android#644]
* Receive a shareMessage (msg + share)
 * share is stored as new share (displayable infos : name, size)
* Accept share <-> Autoaccept share from known contacts
 * download FileMetadata -> All infos available
* Share is available, download on user request, may autodownload images and multimedia (limit size, configurable) to display previews...

**Comment by audax** [comment]
@thechauffeur the first implementation will auoaccept all shares and download the FileMetadata and won't have previews and stuff like that.

This is a possible enhancement for the next iteration.

**Comment by mr-gosh** [comment]
Will this also implement a function for recieving shared text snippets or should there be an extra issue for that?

**Comment by audax** [comment]
That issues is over here: https://github.com/Qabel/qabel-android/issues/592
Currently receiving text from other apps in android is disabled because it didn't work.

**Comment by audax** [comment]
Also, @topic: We have previews of shared files in the chat history.

**Comment by thechauffeur** [comment]
I don't see a question here. Is something to do here regarding the release?

**Comment by audax** [comment]
not regarding the release. We just a clarification if the workflow proposed in this issue is ok.

**Comment by thechauffeur** [comment]
IMO it is okay for now the way it is. We will discuss about how to handle shares in the near future anyways (e.g. mounting shares).
