### ISSUE TITLE
Random contact in contact list

### ISSUE THREAD

**Issue by jan-schreib** [Qabel/qabel-android#687]
Some old contact appears in the Qabel Android App after upgrading.
We used the phone with the old Play Store version and then switched to the current beta.
It now shows an old contact which is neither in the phone book, nor has it contacted me.
I created a fresh Qabel Account and ID for this test.

**Comment by jan-schreib** [comment]
Since the contact is a leftover in the invisible part of the address book, could we build something that does not add contacts to Qabel when there is no user visible part of the contact in the address book?

Weird sentence, to clarify:
To not add a contact to Qabel from the address book, when its not visible in the android address book by the user.

I hope you get that.

**Comment by audax** [comment]
@JoGir: Well...can we?

**Comment by audax** [comment]
Yes we can

**Comment by JoGir** [comment]
we can, but then the sync is useless for email. currently more likely feature than bug
