### ISSUE TITLE
Notifications dont disappear if not acknowledged manually

### ISSUE THREAD

**Issue by Rehwanne** [Qabel/qabel-android#717]
Notifications should disappear if i have read the Message i am getting notified about.

**Comment by JoGir** [comment]
Yes it should, looks like a bug in the event system not forward the event to hide the notification.

**Comment by thechauffeur** [comment]
I tried to reproduce this and I guess the Android notifications outside of the app are meant. If so I reproduced this. The icons inside the app got updated correctly while my testing this.
