### ISSUE TITLE
chat: "message sent" time stamp quickly gets out of date

### ISSUE THREAD

**Issue by enkore** [Qabel/qabel-android#719]
The app displays e.g. "0 seconds ago" which won't update for some time (next message / after a minute or so?). The desktop client displays "moments ago" instead, which feels like a better solution.

Label: Eggshell with Romalian type

**Comment by JoGir** [comment]
We can change the minResolution for formatting(helper/Formatter:54) to minutes and add an extra "moments ago" label for 0 minutes

**Comment by thechauffeur** [comment]
Good idea.
