### ISSUE TITLE
Quota shown wrong in settings screen

### ISSUE THREAD

**Issue by thechauffeur** [Qabel/qabel-android#725]
After purchasing 10 GB option this has shown up in Brittas Client. Maybe even before but this is unconfirmed.
![screenshot_20161004-104856](https://cloud.githubusercontent.com/assets/150507/19075673/396e2ee4-8a46-11e6-9466-9d974dbbc86e.png)

**Comment by enkore** [comment]
Shows correctly in desktop; quota values in servers are correct as well.
